image: node:18

linting:
  script:
    - npm install
    - npm run lint

unit test:
  cache:
    untracked: true
    policy: pull
  script:
    - npm install
    - npm test

code coverage:
  script:
    - npm install
    - npm run coverage